<MyRoot>:

    card_label: card_label

    BoxLayout:
        orientation: 'vertical'
        Label:
            text: "FlashCard"
            font_size: 128
            color: 1, 0.18, 0.28
        Label:
            id: card_label
            text: "-"
            font_size: 64
        Button:
            text: "test"
            font_size: 64
            size: 100, 50
            on_press: root.show_card()